name: CI

env:
  # Branching
  is-merge: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

  # Node.js
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group on branch name (`refs/heads/main`)
  # - Is pull request? Group on pull request branch name, for example `feat/add-awesome-feature`
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.ref
        || github.head_ref
    }}
  # Run merge workflows in sequence to prevent parallel deployments and releases
  # Cancel stale pull request runs in progress for the same branch
  cancel-in-progress: ${{ github.event_name != 'push' }}

permissions:
  # Required by nrwl/nx-set-shas
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.7
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.7
    with:
      number-of-agents: 3
      
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          # fetch all history for all branches and tags
          fetch-depth: 0
      - name:
          'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Build application if affected by changes in feature branch'
        if: env.is-pull-request == 'true'
        run: yarn affected:build
      - name: 'Merge: Build application'
        if: env.is-merge == 'true'
        run: yarn build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0
      - name:
          'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Lint Nx workspace
        run: yarn nx workspace-lint
      - name: 'PR: Lint workspace and affected projects'
        if: env.is-pull-request == 'true'
        run: yarn affected:lint
      - name: 'Merge: Lint workspace and all projects'
        if: env.is-merge == 'true'
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0
      - name:
          'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 'PR: Test affected projects'
        if: env.is-pull-request == 'true'
        run: yarn test
      - name: 'Merge: Test all projects'
        if: env.is-merge == 'true'
        run: yarn test

  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # Required by nrwl/nx-set-shas
          fetch-depth: 0
      - name:
          'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v2
      - name: Set up dependencies
        uses: ./.github/actions/setup-dependencies

      - name:
          'PR: End-to-end test application if affected by changes in feature
          branch'
        if: env.is-pull-request == 'true'
        run: yarn affected:e2e --configuration=ci-production
      - name: 'Merge: End-to-end test application'
        if: env.is-merge == 'true'
        run: yarn e2e --configuration=ci-production